"""Tools for summarizing market research PDFs into structured insights."""

from market_pdf_insights.australian_connectors import (
    ABSDataConnector,
    ABSLocalReleaseConnector,
    ASICMediaReleasesConnector,
    ASXAnnouncementsConnector,
    AustralianDisabledConnectorInstructions,
    MarketIndexConnector,
    RBAFeedConnector,
    RBAFeedKind,
    abs_data_source,
    abs_release_export_source,
    asic_media_source,
    asx_disabled_source,
    market_index_disabled_source,
    rba_source,
)
from market_pdf_insights.insight_schema import (
    KeyClaim,
    MacroAssumption,
    MarketInsightReport,
    MentionedAsset,
    Risk,
    VerificationItem,
)
from market_pdf_insights.ingestion import (
    ConnectorResult,
    IngestionRun,
    IngestionRunner,
    JsonAPIConnector,
    JsonlMarketItemStore,
    LocalFixtureConnector,
    MarketSourceConnector,
    NormalizedMarketItem,
    RSSFeedConnector,
    RawSourceItem,
    build_deduplication_key,
    deduplicate_items,
    normalize_source_item,
    parse_datetime,
)
from market_pdf_insights.llm_client import (
    LLMConfigurationError,
    LLMResponseValidationError,
    LLMSummarizationError,
    MockLLMClient,
    OpenAISummaryClient,
    PlaceholderLLMClient,
)
from market_pdf_insights.pdf_loader import extract_pdf_text
from market_pdf_insights.report_rendering import render_markdown_report, render_terminal_summary
from market_pdf_insights.source_policy import (
    DEFAULT_GUARDRAILS,
    AdviceBoundary,
    MarketIntelligenceGuardrails,
    SourceAccessMethod,
    SourceAttribution,
    SourcePolicyError,
    SourceUsePolicy,
)
from market_pdf_insights.source_registry import (
    SourceAuthType,
    SourceCapability,
    SourceCategory,
    SourceCredentialPolicy,
    SourceDefinition,
    SourceFetchResult,
    SourceRegistry,
    SourceTerms,
    default_source_registry,
)
from market_pdf_insights.summarizer import MarketPdfSummarizer, summarize_pdf

__all__ = [
    "ABSDataConnector",
    "ABSLocalReleaseConnector",
    "ASICMediaReleasesConnector",
    "ASXAnnouncementsConnector",
    "AustralianDisabledConnectorInstructions",
    "KeyClaim",
    "LLMConfigurationError",
    "LLMResponseValidationError",
    "LLMSummarizationError",
    "MacroAssumption",
    "MarketInsightReport",
    "MarketIntelligenceGuardrails",
    "MarketPdfSummarizer",
    "MentionedAsset",
    "MockLLMClient",
    "OpenAISummaryClient",
    "PlaceholderLLMClient",
    "Risk",
    "ConnectorResult",
    "IngestionRun",
    "IngestionRunner",
    "JsonAPIConnector",
    "JsonlMarketItemStore",
    "LocalFixtureConnector",
    "MarketIndexConnector",
    "SourceAccessMethod",
    "SourceAuthType",
    "SourceAttribution",
    "SourceCapability",
    "SourceCategory",
    "SourceCredentialPolicy",
    "SourceDefinition",
    "SourceFetchResult",
    "SourcePolicyError",
    "SourceRegistry",
    "SourceTerms",
    "SourceUsePolicy",
    "MarketSourceConnector",
    "NormalizedMarketItem",
    "RawSourceItem",
    "RBAFeedConnector",
    "RBAFeedKind",
    "RSSFeedConnector",
    "VerificationItem",
    "AdviceBoundary",
    "DEFAULT_GUARDRAILS",
    "abs_data_source",
    "abs_release_export_source",
    "asic_media_source",
    "asx_disabled_source",
    "build_deduplication_key",
    "default_source_registry",
    "deduplicate_items",
    "extract_pdf_text",
    "market_index_disabled_source",
    "normalize_source_item",
    "parse_datetime",
    "rba_source",
    "render_markdown_report",
    "render_terminal_summary",
    "summarize_pdf",
]

__version__ = "0.1.0"
