"""Placeholder LLM client interfaces and deterministic summarization."""

from __future__ import annotations

from collections import Counter
from pathlib import Path
import re
from typing import Protocol, Sequence

from market_pdf_insights.insight_schema import (
    KeyClaim,
    MacroAssumption,
    MarketInsightReport,
    MentionedAsset,
    Risk,
    VerificationItem,
)


class SummaryClient(Protocol):
    """Protocol implemented by clients that can summarize document chunks."""

    def summarize_chunks(
        self,
        chunks: Sequence[str],
        *,
        source_file: str,
    ) -> MarketInsightReport:
        """Summarize text chunks from a source document."""


class PlaceholderLLMClient:
    """Deterministic summarizer used until a hosted LLM implementation exists."""

    model_name = "placeholder"

    def summarize_chunks(
        self,
        chunks: Sequence[str],
        *,
        source_file: str,
    ) -> MarketInsightReport:
        """Build a structured summary from chunks using simple text heuristics."""

        combined_text = _remove_page_markers(" ".join(chunks))
        sentences = _split_sentences(combined_text)
        executive_summary = " ".join(_first_sentences(sentences, limit=3))
        supporting_evidence = _first_sentences(sentences, limit=5)
        risk_sentences = _sentences_matching(sentences, _RISK_TERMS, limit=5)
        macro_sentences = _sentences_matching(sentences, _MACRO_TERMS, limit=5)
        key_claims = _extract_key_claims(sentences)
        if not key_claims and supporting_evidence:
            key_claims = [
                KeyClaim(
                    claim=supporting_evidence[0],
                    stance=_infer_sentence_stance(supporting_evidence[0]),
                    supporting_evidence=[supporting_evidence[0]],
                    confidence_score=0.45,
                )
            ]

        return MarketInsightReport(
            source_file=source_file,
            document_title=_infer_document_title(source_file, sentences),
            executive_summary=executive_summary
            or "No summary could be generated from the extracted document text.",
            market_stance=_infer_market_stance(combined_text),
            key_claims=key_claims,
            supporting_evidence=supporting_evidence,
            risks=[
                Risk(
                    description=sentence,
                    severity=_infer_risk_severity(sentence),
                    evidence=[sentence],
                    affected_assets=_extract_affected_assets(sentence),
                )
                for sentence in risk_sentences
            ],
            sectors_mentioned=_extract_sectors(combined_text),
            companies_or_tickers_mentioned=_extract_asset_mentions(combined_text),
            macro_assumptions=[
                MacroAssumption(
                    assumption=sentence,
                    indicator=_infer_macro_indicator(sentence),
                    direction=_infer_macro_direction(sentence),
                    evidence=[sentence],
                )
                for sentence in macro_sentences
            ],
            numbers_to_verify=_extract_numbers_to_verify(sentences),
            unanswered_questions=_infer_unanswered_questions(combined_text),
            confidence_score=0.35,
            metadata={
                "chunk_count": len(chunks),
                "model": self.model_name,
                "summary_warning": (
                    "Generated by a placeholder summarizer; review against the source document."
                ),
            },
        )


_SECTOR_TERMS = {
    "communication services": ["telecom", "media", "advertising", "communication services"],
    "consumer discretionary": ["retail", "consumer discretionary", "auto", "travel"],
    "consumer staples": ["consumer staples", "supermarket", "food", "beverage"],
    "energy": ["energy", "oil", "gas", "lng", "coal"],
    "financials": ["bank", "banks", "insurance", "financials", "lender"],
    "health care": ["health care", "healthcare", "biotech", "pharmaceutical", "medical"],
    "industrials": ["industrial", "infrastructure", "transport", "logistics"],
    "information technology": ["software", "semiconductor", "technology", "tech", "ai"],
    "materials": ["materials", "gold", "copper", "lithium", "uranium", "mining"],
    "real estate": ["real estate", "reit", "property"],
    "utilities": ["utilities", "utility", "electricity", "grid"],
}

_MARKET_THEME_TERMS = {
    "earnings": ["earnings", "profit", "revenue", "margin", "guidance"],
    "interest rates": ["interest rate", "rates", "bond yield", "yield"],
    "inflation": ["inflation", "cpi", "prices"],
    "commodities": ["gold", "oil", "copper", "lithium", "uranium", "commodity"],
    "valuation": ["valuation", "multiple", "discount", "premium"],
    "growth": ["growth", "expansion", "market share"],
    "capital management": ["buyback", "dividend", "capital raise", "balance sheet"],
}

_BULLISH_TERMS = [
    "attractive",
    "benefit",
    "growth",
    "improvement",
    "opportunity",
    "outperform",
    "recovery",
    "resilient",
    "tailwind",
    "upgrade",
    "upside",
]

_BEARISH_TERMS = [
    "decline",
    "downgrade",
    "downside",
    "headwind",
    "pressure",
    "restrictive",
    "risk",
    "risks",
    "uncertain",
    "volatility",
    "weakness",
]

_RISK_TERMS = [
    "risk",
    "risks",
    "headwind",
    "pressure",
    "decline",
    "downgrade",
    "uncertain",
    "volatility",
]

_MACRO_TERMS = [
    "bond yield",
    "cpi",
    "employment",
    "gdp",
    "inflation",
    "interest rate",
    "oil",
    "rates",
    "unemployment",
    "wage",
    "yield",
]

_RISING_TERMS = ["higher", "increase", "increasing", "rising", "rose", "up"]
_FALLING_TERMS = ["cut", "decline", "decrease", "fall", "falling", "lower", "reduced"]
_STABLE_TERMS = ["flat", "steady", "stable", "unchanged"]
_VOLATILE_TERMS = ["uncertain", "volatile", "volatility", "swing"]

_TICKER_PATTERN = re.compile(r"\b[A-Z]{2,5}\b")
_NUMBER_PATTERN = re.compile(
    r"(?:[$€£]\s?\d[\d,]*(?:\.\d+)?|\d+(?:\.\d+)?\s?(?:%|bps|bp|million|billion|bn|m|x))",
    re.IGNORECASE,
)
_PAGE_MARKER_PATTERN = re.compile(r"---\s*Page\s+\d+\s*---", re.IGNORECASE)


def _split_sentences(text: str) -> list[str]:
    """Split text into readable sentence-like fragments."""

    fragments = re.split(r"(?<=[.!?])\s+", text.strip())
    return [fragment.strip() for fragment in fragments if fragment.strip()]


def _remove_page_markers(text: str) -> str:
    """Remove extraction page markers before summarization heuristics run."""

    return _PAGE_MARKER_PATTERN.sub(" ", text)


def _first_sentences(sentences: Sequence[str], *, limit: int) -> list[str]:
    """Return the first sentence fragments up to a given limit."""

    return list(sentences[:limit])


def _infer_document_title(source_file: str, sentences: Sequence[str]) -> str:
    """Infer a readable document title from the first heading or file name."""

    for sentence in sentences[:3]:
        title = sentence.strip("- \n\t")
        if 4 <= len(title) <= 120 and len(title.split()) <= 14:
            return title
    return Path(source_file).stem.replace("-", " ").replace("_", " ").title()


def _extract_sectors(text: str) -> list[str]:
    """Find known market sectors present in the source text."""

    lowered = text.lower()
    sectors = [
        sector
        for sector, terms in _SECTOR_TERMS.items()
        if any(term in lowered for term in terms)
    ]
    return sectors[:8]


def _extract_asset_mentions(text: str) -> list[MentionedAsset]:
    """Extract likely all-caps ticker symbols from the source text."""

    ignored = {"ASX", "CEO", "CFO", "ETF", "GDP", "LLM", "PDF", "USD"}
    counts = Counter(
        match.group(0)
        for match in _TICKER_PATTERN.finditer(text)
        if match.group(0) not in ignored
    )
    mentions = [
        MentionedAsset(name=ticker, ticker=ticker, asset_type="company", sentiment="unclear")
        for ticker, _count in counts.most_common(10)
    ]
    return mentions


def _extract_key_claims(sentences: Sequence[str]) -> list[KeyClaim]:
    """Convert the most informative early sentences into key claims."""

    claims: list[KeyClaim] = []
    candidate_terms = _BULLISH_TERMS + _BEARISH_TERMS + list(_flatten_terms(_MARKET_THEME_TERMS))
    for sentence in sentences:
        if not _contains_any(sentence, candidate_terms):
            continue
        stance = _infer_sentence_stance(sentence)
        claims.append(
            KeyClaim(
                claim=sentence,
                stance=stance,
                supporting_evidence=[sentence],
                confidence_score=0.5 if stance == "unclear" else 0.55,
            )
        )
        if len(claims) >= 5:
            break
    return claims


def _infer_market_stance(text: str) -> str:
    """Infer a coarse market stance from bullish and bearish language."""

    lowered = text.lower()
    bullish_count = sum(lowered.count(term) for term in _BULLISH_TERMS)
    bearish_count = sum(lowered.count(term) for term in _BEARISH_TERMS)
    if bullish_count and bearish_count:
        return "mixed"
    if bullish_count:
        return "bullish"
    if bearish_count:
        return "bearish"
    return "neutral" if lowered.strip() else "unclear"


def _infer_sentence_stance(sentence: str) -> str:
    """Infer a coarse stance for one sentence."""

    has_bullish = _contains_any(sentence, _BULLISH_TERMS)
    has_bearish = _contains_any(sentence, _BEARISH_TERMS)
    if has_bullish and has_bearish:
        return "mixed"
    if has_bullish:
        return "bullish"
    if has_bearish:
        return "bearish"
    return "unclear"


def _infer_risk_severity(sentence: str) -> str:
    """Infer risk severity from wording."""

    lowered = sentence.lower()
    if any(term in lowered for term in ["material", "significant", "severe", "major"]):
        return "high"
    if any(term in lowered for term in ["minor", "limited", "modest"]):
        return "low"
    return "medium"


def _extract_affected_assets(sentence: str) -> list[str]:
    """Extract likely affected tickers from a risk sentence."""

    return [
        match.group(0)
        for match in _TICKER_PATTERN.finditer(sentence)
        if match.group(0) not in {"ASX", "CEO", "CFO", "ETF", "GDP", "LLM", "PDF", "USD"}
    ][:5]


def _infer_macro_indicator(sentence: str) -> str | None:
    """Infer the primary macro indicator in a sentence."""

    lowered = sentence.lower()
    for theme, terms in _MARKET_THEME_TERMS.items():
        if theme in {"interest rates", "inflation", "commodities"} and any(
            term in lowered for term in terms
        ):
            return theme
    if "gdp" in lowered:
        return "GDP"
    if "employment" in lowered or "unemployment" in lowered:
        return "employment"
    return None


def _infer_macro_direction(sentence: str) -> str:
    """Infer macro direction from wording."""

    lowered = sentence.lower()
    if any(term in lowered for term in _VOLATILE_TERMS):
        return "volatile"
    if any(term in lowered for term in _RISING_TERMS):
        return "rising"
    if any(term in lowered for term in _FALLING_TERMS):
        return "falling"
    if any(term in lowered for term in _STABLE_TERMS):
        return "stable"
    return "unclear"


def _extract_numbers_to_verify(sentences: Sequence[str]) -> list[VerificationItem]:
    """Extract notable numbers that should be checked against source data."""

    items: list[VerificationItem] = []
    seen: set[tuple[str, str]] = set()
    for sentence in sentences:
        for match in _NUMBER_PATTERN.finditer(sentence):
            number = match.group(0)
            key = (number.casefold(), sentence.casefold())
            if key in seen:
                continue
            seen.add(key)
            items.append(
                VerificationItem(
                    number=number,
                    context=sentence,
                    source_excerpt=sentence,
                    priority="high" if "%" in number or "$" in number else "medium",
                )
            )
            if len(items) >= 10:
                return items
    return items


def _infer_unanswered_questions(text: str) -> list[str]:
    """Flag follow-up checks implied by the extracted content."""

    questions: list[str] = []
    if _NUMBER_PATTERN.search(text):
        questions.append("Which source tables or filings confirm the extracted numerical claims?")
    if _contains_any(text, _RISK_TERMS):
        questions.append("Which risks are most material to the report's overall stance?")
    return questions[:4]


def _sentences_matching(
    sentences: Sequence[str],
    terms: Sequence[str],
    *,
    limit: int,
) -> list[str]:
    """Return sentences containing any of the requested lower-case terms."""

    matches: list[str] = []
    for sentence in sentences:
        lowered = sentence.lower()
        if any(term in lowered for term in terms):
            matches.append(sentence)
        if len(matches) >= limit:
            break
    return matches


def _contains_any(text: str, terms: Sequence[str]) -> bool:
    """Return whether text contains any lower-case search term."""

    lowered = text.lower()
    return any(term in lowered for term in terms)


def _flatten_terms(term_groups: dict[str, list[str]]) -> list[str]:
    """Flatten term groups into one list."""

    return [term for terms in term_groups.values() for term in terms]
