"""Placeholder LLM client interfaces and deterministic summarization."""

from __future__ import annotations

from collections import Counter
import re
from typing import Protocol, Sequence

from market_pdf_insights.insight_schema import (
    CompanyMention,
    MarketInsightSummary,
    SummarySection,
)


class SummaryClient(Protocol):
    """Protocol implemented by clients that can summarize document chunks."""

    def summarize_chunks(
        self,
        chunks: Sequence[str],
        *,
        source_file: str,
    ) -> MarketInsightSummary:
        """Summarize text chunks from a source document."""


class PlaceholderLLMClient:
    """Deterministic summarizer used until a hosted LLM implementation exists."""

    model_name = "placeholder"

    def summarize_chunks(
        self,
        chunks: Sequence[str],
        *,
        source_file: str,
    ) -> MarketInsightSummary:
        """Build a structured summary from chunks using simple text heuristics."""

        combined_text = " ".join(chunks)
        sentences = _split_sentences(combined_text)
        executive_summary = " ".join(_first_sentences(sentences, limit=3))
        key_themes = _extract_key_themes(combined_text)
        company_mentions = _extract_company_mentions(combined_text)
        risks = _sentences_matching(sentences, _RISK_TERMS, limit=5)
        opportunities = _sentences_matching(sentences, _OPPORTUNITY_TERMS, limit=5)

        sections = [
            SummarySection(
                title="Document Highlights",
                bullets=_first_sentences(sentences, limit=5),
            )
        ]

        return MarketInsightSummary(
            source_file=source_file,
            executive_summary=executive_summary
            or "No summary could be generated from the extracted document text.",
            key_themes=key_themes,
            company_mentions=company_mentions,
            risks=risks,
            opportunities=opportunities,
            disclaimers=[
                "Generated by a placeholder summarizer; review against the source document."
            ],
            sections=sections,
            metadata={
                "chunk_count": len(chunks),
                "model": self.model_name,
            },
        )


_THEME_TERMS = {
    "earnings": ["earnings", "profit", "revenue", "margin", "guidance"],
    "interest rates": ["interest rate", "rates", "bond yield", "yield"],
    "inflation": ["inflation", "cpi", "prices"],
    "commodities": ["gold", "oil", "copper", "lithium", "uranium", "commodity"],
    "valuation": ["valuation", "multiple", "discount", "premium"],
    "growth": ["growth", "expansion", "market share"],
    "capital management": ["buyback", "dividend", "capital raise", "balance sheet"],
}

_RISK_TERMS = [
    "risk",
    "risks",
    "headwind",
    "pressure",
    "decline",
    "downgrade",
    "uncertain",
    "volatility",
]

_OPPORTUNITY_TERMS = [
    "opportunity",
    "opportunities",
    "upside",
    "growth",
    "tailwind",
    "upgrade",
    "recovery",
    "attractive",
]

_TICKER_PATTERN = re.compile(r"\b[A-Z]{2,5}\b")


def _split_sentences(text: str) -> list[str]:
    """Split text into readable sentence-like fragments."""

    fragments = re.split(r"(?<=[.!?])\s+", text.strip())
    return [fragment.strip() for fragment in fragments if fragment.strip()]


def _first_sentences(sentences: Sequence[str], *, limit: int) -> list[str]:
    """Return the first sentence fragments up to a given limit."""

    return list(sentences[:limit])


def _extract_key_themes(text: str) -> list[str]:
    """Find known market themes present in the source text."""

    lowered = text.lower()
    themes = [
        theme
        for theme, terms in _THEME_TERMS.items()
        if any(term in lowered for term in terms)
    ]
    return themes[:8]


def _extract_company_mentions(text: str) -> list[CompanyMention]:
    """Extract likely all-caps ticker symbols from the source text."""

    ignored = {"ASX", "CEO", "CFO", "ETF", "GDP", "LLM", "PDF", "USD"}
    counts = Counter(
        match.group(0)
        for match in _TICKER_PATTERN.finditer(text)
        if match.group(0) not in ignored
    )
    mentions = [
        CompanyMention(name=ticker, ticker=ticker, sentiment="unknown")
        for ticker, _count in counts.most_common(10)
    ]
    return mentions


def _sentences_matching(
    sentences: Sequence[str],
    terms: Sequence[str],
    *,
    limit: int,
) -> list[str]:
    """Return sentences containing any of the requested lower-case terms."""

    matches: list[str] = []
    for sentence in sentences:
        lowered = sentence.lower()
        if any(term in lowered for term in terms):
            matches.append(sentence)
        if len(matches) >= limit:
            break
    return matches
